# enable mouse
set -g mouse on

# theming and layout
set -g status-position top
set -g allow-passthrough on

# windows and panes
set -g base-index 1
setw -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows 1
setw -g aggressive-resize on
set -g focus-events on

# shell
set -g default-shell $SHELL
set -g default-command $SHELL

# plugins
set-environment -g TMUX_DATA_DIR '~/.local/share/tmux'
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'
set-environment -g CLAUDE_CODE_TMUX_TRUECOLOR true
set-environment -g CLAUDE_CODE_NO_FLICKER true
# set-environment -g CLAUDE_CODE_DISABLE_MOUSE true

# yank to system clipboard (and over ssh)
set -g set-clipboard on
set -g @yank_selection 'clipboard'

# better timings
set -s escape-time 0
set -g display-time 4000
set -g status-interval 50000
set -g lock-after-time 3600

# increase history limit
set -g history-limit 50000

# environment
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# extended keys
set -g extended-keys on
set -g extended-keys-format xterm
set -as terminal-features ',xterm*:extkeys'

# special shift+enter behaviour for claude code
# due to the lack of kitty keyboard protocol support in tmux
bind-key -T root S-Enter send-keys C-j
